### ISSUE TITLE
Highlighting wrong component with tab indentation

### ISSUE THREAD

**Issue by neerolyte** [timonwong/vscode-shellcheck#10]
With tabbed indentation the green squiggle seems to always end up in the wrong spot:

![image](https://user-images.githubusercontent.com/1070702/39785404-65d32cf8-535f-11e8-80ec-df1cdfa11021.png)

With spaces for indentation the green squiggle is in the right spot:

![image](https://user-images.githubusercontent.com/1070702/39785428-7e5f52b0-535f-11e8-835e-e9965adcac93.png)

**Comment by timonwong** [comment]
Thanks for reporting, it's a bug. A new version will be released soon.
