### ISSUE TITLE
Add an option to ignore certain files

### ISSUE THREAD

**Issue by mikeroll** [timonwong/vscode-shellcheck#15]
It would be great to have a glob `shellcheck.excludeFiles` option to ignore known "bad" files, 3rd-party files, unsupported shell scripts etc. I.e. don't run shellcheck for those files at all to avoid cluttering the Problems view.

**Comment by timonwong** [comment]
`v0.5.0` released with this feature, please have a look at `"shellcheck.ignorePatterns"`. It shares the same syntax as `"files.exclude"`.

**Comment by mikeroll** [comment]
@timonwong Thank you! However, the matcher seems to skip files/folders starting with a period.
From what I see, this is just a matter of setting the `dot` minimatch option: https://github.com/isaacs/minimatch#dot
