### ISSUE TITLE
identify script file to be linted by shebang alone

### ISSUE THREAD

**Issue by dkebler** [timonwong/vscode-shellcheck#156]
In atom I use a shellcheck linter extension and it can identify a bash shell file to lint solely based on the existence of the shebang without need of a common extension like `.sh`.  https://atom.io/packages/linter-shellcheck

As a matter of organization I don't always want to use the .sh extension on my script files but always include the shebang.

Does the extension support this?  If so how do I enable?  If not it should be added (I might be the one to write a PR if I can get some help).

**Comment by felipecrs** [comment]
Yes, it works. This is a VS Code built-in feature.

![7zicYQNCOq](https://user-images.githubusercontent.com/29582865/106309497-fc953d00-6240-11eb-836f-dfa6934731ed.gif)

**Comment by dkebler** [comment]
ok then I have a problem.

```
#!/bin/bash
export CHROME_CONFIG_HOME="/opt/Chromium"
```
 filename is just `env` 

problems tab says

`Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.`

it's not working for me.

**Comment by dkebler** [comment]
![image](https://user-images.githubusercontent.com/1316185/106312178-1f145f80-621b-11eb-9d58-a585730f56a8.png)

**Comment by dkebler** [comment]
btw the same file is not recognized by shell-format extension either

**Comment by felipecrs** [comment]
This is because files named `env` are recognized as "dotenv" files.

**Comment by dkebler** [comment]
The one filename that won't work and I used it!  yes changing filename fixed it.    This is not the case with `env` in atom so will do as you suggest. Thx

**Comment by felipecrs** [comment]
Feel free to reference this issue once you open the new one. I'll support you with a 👍.
