### ISSUE TITLE
Failed to run shellcheck, Command timed out after 2000 milliseconds

### ISSUE THREAD

**Issue by marveloo** [timonwong/vscode-shellcheck#179]
When starting VS Code, occasionally shellcheck fails to start:
```
Failed to run shellcheck: [ETIMEDOUT] Command timed out after 2000 milliseconds: /home/user/.vscode-server/extensions/timonwong.shellcheck-0.13.3/binaries/linux/x64/shellcheck -V spawnSync /home/user/.vscode-server/extensions/timonwong.shellcheck-0.13.3/binaries/linux/x64/shellcheck ETIMEDOUT
```
<hr>

Windows 10
VS Code 1.54.1 (with Remote - WSL)
ShellCheck 0.13.3

**Comment by felipecrs** [comment]
Interesting. Are you able to reproduce the issue if you want?

**Comment by felipecrs** [comment]
My theory is:

When your VS Code starts, it may be loading a bunch of extensions, and therefore it slows down your computer. Then, occasionally, 2 seconds is not enough to get a response from shellcheck -V.
