### ISSUE TITLE
[FeatureRequest] Provide setting option to shellcheck wiki link

### ISSUE THREAD

**Issue by loynoir** [timonwong/vscode-shellcheck#193]
Would be nice to able to setting custom shellcheck wiki link. 
Eg,
from `https://www.shellcheck.net/wiki/${ruleId}`
to `https://github.com/koalaman/shellcheck/wiki/${ruleId}`.

But now seems hardcoded. 
https://github.com/timonwong/vscode-shellcheck/blob/3a803d31912b863985405da042339db98fda0c56/src/linter.ts#L233

Besides, `https://www.shellcheck.net/wiki/${ruleId}` seems always redirect to `https://github.com/koalaman/shellcheck/wiki/${ruleId}`.

**Comment by felipecrs** [comment]
Hi @loynoir, do you know a use case for this?

**Comment by loynoir** [comment]
As from my side, 
1. `https://www.shellcheck.net/wiki/${ruleId}` seems always redirect to `https://github.com/koalaman/shellcheck/wiki/${ruleId}`
2. `https://www.shellcheck.net/wiki/${ruleId}` is way more slower than `https://github.com/koalaman/shellcheck/wiki/${ruleId}`
3. shellcheck repo is on `https://github.com/koalaman/shellcheck`

**Comment by felipecrs** [comment]
> 2\. From my side, `https://www.shellcheck.net/wiki/${ruleId}` is way more slower than `https://github.com/koalaman/shellcheck/wiki/${ruleId}`. First connection stuck.

It may be worth to report as an issue to https://github.com/koalaman/shellcheck.net.

We could consider switching the default to the GitHub one directly, but I think @koalaman's goal at `https://www.shellcheck.net/wiki` was to prevent a move on the repository name or owner to break someone relying on `https://github.com/koalaman/shellcheck/wiki/${ruleId}`, or to allow moving to somewhere else than the wiki without breaking as  well.
