### ISSUE TITLE
SC1056,1072 Flags `|, &&, ||` after Line Continuation

### ISSUE THREAD

**Issue by adamgranthendry** [timonwong/vscode-shellcheck#233]
OS: Windows 10 Enterprise, Version 1909, Build 18363.1556
VSCode Version: 1.56.2
Shellcheck Version: 0.7.2 (installed from `.zip` on GitHub)

The following code works on `shellcheck.net`, but fails in VSCode on Windows:

```
_my_test() {
  echo '1 2 3' \
  |cut -d' ' -f2
}
```

Errors at the `|`, expecting a `}`. Operators are required on new line per the CONTRIBUTING guidelines I am following for code readability (similar to putting operators on new line in Python)

**Comment by felipecrs** [comment]
Probably due to CRLF line endings, can you try with the CLI?

**Comment by adamgranthendry** [comment]
@felipecrs I can confirm it occurs with the CLI. Please also see https://github.com/koalaman/shellcheck/issues/2239. This is definitely something with `shellcheck` on Windows as opposed to just the VSCode Extension.

**Comment by adamgranthendry** [comment]
@felipecrs I can confirm switching from `CRLF` to `LF` in VSCode as you showed solves my problem. Thank you for this great tip! This issue can be closed now.

**Comment by adamgranthendry** [comment]
Solved by switching `CRLF` to `LF` in VSCode.
