### ISSUE TITLE
SC1041,1042 Cannot Find 'EOF' with Output Redirection on Same Line

### ISSUE THREAD

**Issue by adamgranthendry** [timonwong/vscode-shellcheck#234]
OS: Windows 10 Enterprise, Version 1909, Build 18363.1556
VSCode Version: 1.56.2
Shellcheck Version: 0.7.2 (installed from .zip on GitHub)

The following code works on shellcheck.net, but fails in VSCode on Windows:

```
#! /bin/sh -

my_file_='example.txt'

# Overcoming a strange Cygwin error
command cat <<EOF >"${my_file_}"
#! /bin/sh
exit 0
EOF
```

This could be fixed by putting >"${my_file_}" before `<<EOF`, but the bigger issue is VSCode sees 'EOF\r' at end (NOTE: This is not fixed by ignoring carriage-return/new-lines errors with `# shellcheck disable=SC1017`. Furthermore, the above code works on shellcheck.net, so I believe the problem is with the VSCode extension.

**Comment by felipecrs** [comment]
Can you try using the ShellCheck CLI?

**Comment by felipecrs** [comment]
Also, I believe Cygwin and MSYS can deal with just LF ending shell scripts. If that's true, you can try to convert your scripts from CRLF to LF line endings. You can do this with VS Code, simply click in:

![image](https://user-images.githubusercontent.com/29582865/119574696-407df600-bd8c-11eb-9c2e-4d94a0ab00c9.png)

**Comment by adamgranthendry** [comment]
@felipecrs I can confirm this happens on the CLI. For reference, please also see my other issue posted here: https://github.com/koalaman/shellcheck/issues/2240. I will try converting CRLF to LF on VSCode and report back.

**Comment by adamgranthendry** [comment]
@felipecrs Thank you! I can confirm switching from `CRLF` to `LF` resolves this issue.

**Comment by felipecrs** [comment]
That's cool to hear, @adamgranthendry. Did you also try to execute your scripts in Cygwin just to confirm if they are still working?

**Comment by adamgranthendry** [comment]
@felipecrs I wrote the scripts in Cygwin real quick with Vim and they worked (shellcheck returned nothing, which I'm assuming means no errors)
