### ISSUE TITLE
Support Docker version of Shellcheck

### ISSUE THREAD

**Issue by mikemol** [timonwong/vscode-shellcheck#24]
So, I'm a Mac user, specifically a Macports user, not a brew user. So installing the latest `shellcheck` [is difficult right now](https://trac.macports.org/ticket/51568).

That said, I _can_ use Docker, and there is a [Docker container for Shellcheck](https://hub.docker.com/r/koalaman/shellcheck/). So I threw together a shim:

```bash
#!/bin/sh
if [[ ! -e "${1}" ]] ; then
  docker run koalaman/shellcheck:stable "${1}"
  exit $?
fi

filepath=$(dirname "${1}")
filepath=${filepath:+$(pwd)} # Use current working directory if no path in argument

filename=$(basename "${1}")
docker run --mount type=bind,source="${filepath}",target=/mnt koalaman/shellcheck:stable /mnt/${filename}
```

This functions absolutely fine for me on the command line, but it doesn't seem to function with the Visual Studio Code extension.

It would be super helpful if `vscode-shellcheck` were able to grab the latest `shellcheck` docker image and use that instead.

**Comment by timonwong** [comment]
Mounting will not work because this extension uses "pipe", you can try to use`-i` in your docker command.

**Comment by cailloumajor** [comment]
Same problem here, with the shim below, located in `~/.local/bin/` (VSCode setting `shellcheck.executablePath` set accordingly, i.e. `/home/ME/.local/bin/shellcheck`) :
```shell
#!/bin/sh

filepath="$(dirname ${1})"
filepath="${filepath:+$(pwd)}"

filename="$(basename ${1})"
docker run --rm -i -v "$filepath:/mnt" koalaman/shellcheck:v0.5.0 $filename
```
* With above configuration, nothing seems to happen regarding linting when opening a shell file.
* With `shellcheck` binary installed in `$PATH` (`shellcheck.executablePath` left as default), linting works.

A last thing to note : if I remove `--rm` flag from  `docker run` invocation inside the shim, I can see created containers when linting is triggered, meaning the shim is called.

**Comment by timonwong** [comment]
The vscode extension uses pipes, that is, it "pipes" shell source to shellcheck binary directly, through "stdin".
So in order to get that work:
1. It possible to make docker work with "stdin".
2. You don't need the filename, actually, the filename is "-", and will be passed automatically in this extension.

https://github.com/timonwong/vscode-shellcheck/blob/6327fd66804bba7aae93963a78b713109d477f3e/src/linter.ts#L270

So, a simple shim script may look like:

```bash
#!/bin/bash

docker run --rm -i koalaman/shellcheck:v0.5.0 "$@"
```

**Comment by cailloumajor** [comment]
@timonwong it works with your solution, thanks.
