### ISSUE TITLE
shellcheck not found on M1 Mac

### ISSUE THREAD

**Issue by bhrutledge** [timonwong/vscode-shellcheck#244]
I'm getting this error when I open a shell script:

> The shellcheck program was not found (not installed?). Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'

I have `shellcheck` installed via Homebrew:

```
% which shellcheck
/opt/homebrew/bin/shellcheck
```

Poking around a bit, I found what looks like the relevant source:

https://github.com/timonwong/vscode-shellcheck/blob/3a803d31912b863985405da042339db98fda0c56/src/linter.ts#L136

https://github.com/timonwong/vscode-shellcheck/blob/3a803d31912b863985405da042339db98fda0c56/src/linter.ts#L199

From that, I can see that there isn't a binary for the M1 architecture:

```
% tree ~/.vscode/extensions/timonwong.shellcheck-0.14.1/binaries
/Users/bhrutledge/.vscode/extensions/timonwong.shellcheck-0.14.1/binaries
├── darwin
│   └── x64
│       └── shellcheck
├── linux
│   ├── arm
│   │   └── shellcheck
│   ├── arm64
│   │   └── shellcheck
│   └── x64
│       └── shellcheck
└── win32
    └── x32
        └── shellcheck.exe
```

Still, I would have expected the default of `shellcheck` to work. I thought it might be related to my runtime `PATH` not being set properly, but looking at `process.env.PATH` from the VS Code Developer Tools shows that it includes `/opt/homebrew/bin`.

Of course, this is a minor annoyance, because I can set it manually, but it'd be nice if it just worked. 😄

**Comment by felipecrs** [comment]
Did you add `shellcheck` to `shellcheck.executablePath`?

**Comment by bhrutledge** [comment]
Yep, setting `"shellcheck.executablePath": "/opt/homebrew/bin/shellcheck"` works as expected. I just thought this extension might discover it automatically if it was in my `$PATH`, since it looks like that's what the code is intended to do.

For reference, here's the issue for an M1 build of shellcheck: https://github.com/koalaman/shellcheck/issues/2109. As I noted in a comment just now, it's installable natively with Homebrew (as of a couple days ago), so hopefully the shellcheck folks will release an official build.

**Comment by felipecrs** [comment]
Did you try `"shellcheck.executablePath": "shellcheck"`?

**Comment by bhrutledge** [comment]
Ah, yes, that works too.

**Comment by felipecrs** [comment]
But your complain is still valid, the extension should properly find it automatically when the bundled one is not found. I'm going to check.

**Comment by felipecrs** [comment]
@bhrutledge when possible please test this new version to confirm it fixes your issue.

**Comment by bhrutledge** [comment]
Yep! Thank you!

**Comment by lu-yanda** [comment]
still met this issue of shellcheck 0.9, how to set "shellcheck.executablePath": "shellcheck", where should i put

**Comment by lu-yanda** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/99716849/208030004-644f90b6-6588-4384-94d3-b89ff3835691.png">

**Comment by felipecrs** [comment]
@lu-yanda what's this hook, man? Seems like the extension is trying to use this hook (check your vscode settings), and the hook can't find shellcheck installed.

**Comment by Morriz** [comment]
this is still an issue on Sonoma on apple silicon

**Comment by mrk-han** [comment]
I'm seeing this issue in version 37.7, with an Apple M3 Pro. 

**Expectation:** Download this vsix file, load into VSCode, vs-code shellcheck would have a built in binary and would just "work" with no other download needed. (This is what is communicated in the documentation for Arm64)

**Reality:** "The shellcheck program was not found (not installed?). Use the 'shellcheck.executablePath' setting to configure the location of 'shellcheck'.

**Comment by felipecrs** [comment]
> EDIT: This may be because we downloaded a vsix without built in binaries https://github.com/vscode-shellcheck/vscode-shellcheck/issues/845#issuecomment-1338507244

@mrk-han can you double check then? Download the right vsix (darwin-arm64) and try again.

**Comment by mrk-han** [comment]
Will let you know ASAP, hopefully in the next week. Need to get download approved by security for that specific file.

**Comment by mrk-han** [comment]
@felipecrs While I'm waiting to test, I wanted to ask if there's any possibility of having the darwin-arm64 binary available for download from the vscode marketplace? https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck

**Comment by felipecrs** [comment]
They are already there. You can download it from VS Code, or through [this trick](https://stackoverflow.com/a/79565372/12156188).
