### ISSUE TITLE
Does the vscode-shellcheck extension fully support zsh scripting code?

### ISSUE THREAD

**Issue by joeasks** [timonwong/vscode-shellcheck#255]
Does the vscode-shellcheck extension fully support zsh scripting code?

**Comment by felipecrs** [comment]
No, the extension uses the [`shellcheck`](https://github.com/koalaman/shellcheck) to do its work, which in turn does not support ZSH for now. 

https://github.com/koalaman/shellcheck/wiki/SC1071
