### ISSUE TITLE
Setting the executablePath setting no longer works

### ISSUE THREAD

**Issue by fishikles** [timonwong/vscode-shellcheck#256]
When setting the executablePath directly via the setting it is being overridden to "shellcheck"
resulting in the following error:
Failed to run shellcheck: [undefined] Command failed with exit code 1: shellcheck -V 'shellcheck' is not recognized as an internal or external command, operable program or batch file.

this is due to:
https://github.com/timonwong/vscode-shellcheck/commit/d7598a6560ea0e78ed5edf3657d4fe30b486a754

As if executablePath is set isBundled will be False so executablePath will be overriden to 'shellcheck'

I think to do this properly if executablePath is not set you should check for the existence of shellcheck in the path with a fall back to the bundled version.

**Comment by felipecrs** [comment]
Thanks for raising this. https://github.com/timonwong/vscode-shellcheck/pull/257 should solve the issue.

**Comment by fishikles** [comment]
That looks good
Thanks for the quick fix
