### ISSUE TITLE
Scoop path for shellcheck

### ISSUE THREAD

**Issue by rogermartensson** [timonwong/vscode-shellcheck#26]
One of the recommended ways to install shellcheck for windows is to use Scoop. (see shellcheck page)
It would probably be easier for the user to check scoop-installation path by default even though that changing the exec-path isn't that difficult.

**Comment by timonwong** [comment]
If that package manager install apps into your `PATH` environment (I think it should), once installed, I suppose changing "shellcheck.executablePath" to "shellcheck.exe" will just work.

I personally now won't introduce too many platform specific changes. (the WSL is an exception)

**Comment by jwhipp** [comment]
Just to help out anyone looking to get this done, I literally just did a` scoop install shellcheck` then left the settings default and it's working well.  Scoop does install shellcheck in the path, but you could always check that using `Get-Command shellcheck`.

**Comment by rogermartensson** [comment]
I close my issue since I must have done something wrong. Not the first time. ;)
