### ISSUE TITLE
Problem message is missing parts

### ISSUE THREAD

**Issue by rogermartensson** [timonwong/vscode-shellcheck#27]
I found a visual bug in my first script I tested with shellcheck.

![bild](https://user-images.githubusercontent.com/12293031/45950708-36b2fc00-c001-11e8-8a6c-482850b898a1.png)

When  copying the message I get the correct message.:
```
Use $(..) instead of legacy `..`. [SC2006]
```

**Comment by timonwong** [comment]
Hmmm, it seems `$(xxx)` was accidentally interpreted as variables in vscode. I may have to workaround it, thanks.

**Comment by timonwong** [comment]
See Microsoft/vscode#59286

**Comment by timonwong** [comment]
@rogermartensson The latest VSCode insider should address your problem, per Microsoft/vscode#59286
