### ISSUE TITLE
Autofix on save?

### ISSUE THREAD

**Issue by KnifeFed** [timonwong/vscode-shellcheck#273]
Would it be possible to implement autofix on save? I.e., automatically applying Quick Fix on save when `"editor.codeActionsOnSave": { "source.fixAll": true }` is set?

**Comment by felipecrs** [comment]
This is a good suggestion.

**Comment by felipecrs** [comment]
I'm not able to find any guidance on this at the VS Code docs for extension authors.

**Comment by felipecrs** [comment]
References:

https://github.com/microsoft/vscode-typescript-tslint-plugin/commit/90f505ac0afdd6afa1a0b614f2d963936b96f427
