### ISSUE TITLE
Limit of highlighted errors 

### ISSUE THREAD

**Issue by FrancoisXavierNoe** [timonwong/vscode-shellcheck#277]
Hello,
I have more than 600 errors in a legacy source code.
I can see all the errors in the "Problem" window in VS Code, but in the "source code" window I have no more highlighted errors after the line 1015.
![Screen Shot 07-27-21 at 11 37 AM](https://user-images.githubusercontent.com/41744606/127152903-045de9eb-df8a-4ab9-aec9-73d019e153f9.PNG)
I think there is a limit with the highlight.

Can you confirm ? Is it a bug ?

**Comment by felipecrs** [comment]
Is your script open source, so I could test?

Also, does this problem happens when you use the ShellCheck CLI?

**Comment by FrancoisXavierNoe** [comment]
Sorry, it is not an open source script...

but you can easily reproduce the issue by copying the same line 300 times with an error
![Screen Shot 07-27-21 at 06 13 PM](https://user-images.githubusercontent.com/41744606/127189893-b39e9525-79dd-4bed-89dc-87c7e416fb3b.PNG)

You can see that there is a limit with the highlighted errors.

**Comment by felipecrs** [comment]
It turns out to be a VS Code limitation: https://github.com/microsoft/vscode/issues/9826

**Comment by felipecrs** [comment]
I'm going to close this issue in this repository, as it's not the right place.

However, if you think on a solution that would involve changes in the extension rather than in the core VS Code, feel free to suggest and I can reopen this issue.
