### ISSUE TITLE
No ignorePatterns examples provided

### ISSUE THREAD

**Issue by claneys** [timonwong/vscode-shellcheck#32]
Hi,
I wanna use the shellcheck.ignorePatterns extensions settings but can't find any example of which JSON object it expects. So finally go through source code to see that it expects "patterns": bool object. You should IMO, put an simple example in the settings description.

Thanks

**Comment by toulousain79** [comment]
:+1:

**Comment by timonwong** [comment]
See https://github.com/timonwong/vscode-shellcheck/commit/54c2014585c86ecd30b003316b55e596b7496a47
