### ISSUE TITLE
Reporting errors on .git files

### ISSUE THREAD

**Issue by dsifford** [timonwong/vscode-shellcheck#4]
Hello,

Thanks for your work on this extension.

There's been a sort of strange issue that I've run into on a few occasions where the extension reports errors on the currently opened shell file and also its `.git` counterpart. This doesn't happen all the time, but it does happen somewhat frequently.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/5240018/26602760/838201fa-4552-11e7-8b79-a440a7ebaebe.png)

Any ideas?

Thanks in advance!

**Comment by cttwapps** [comment]
Thought it was just me!

**Comment by timonwong** [comment]
Can you provided current options for shellcheck, are you using ` "shellcheck.run": "onSave"?`

**Comment by dsifford** [comment]
@timonwong The only options I'm using is `"shellcheck.customArgs": [ "-x" ]`

**Comment by timonwong** [comment]
@dsifford 
Hmmm... strange, it seems that the file which uri points to `git://xxxxxx` is opened.
for default configuration, lint will only occurs on:
1. Reloading configuration (triggers linting on all open documents)
2. Open file
3. Modify buffer

So it may be caused by an hidden document, can you give me a list of extensions you are currently using? You can retrieve them by typing `code --list-extensions` in your shell.

**Comment by Swift-R** [comment]
Happening to me too...

If you care for that list of extensions, here's mine:

```
EditorConfig.EditorConfig
Shan.code-settings-sync
alefragnani.Bookmarks
alefragnani.project-manager
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
ecodes.vscode-phpmd
felixfbecker.php-intellisense
glen-84.sass-lint
hunter-dev.volt
ikappas.phpcs
lkytal.coffeelinter
mkaufman.HTMLHint
mrmlnc.vscode-duplicate
neilbrayfield.php-docblocker
robertohuertasm.vscode-icons
shardulm94.trailing-spaces
timonwong.shellcheck
zhuangtongfa.Material-theme
```

Also, there's no hidden document, if I understood what you said. This is `ls -alF` on the project directory:

```
mike@Mike-Pro:~/DevA$ ll
total 96
drwxr-xr-x  10 mike  staff   320B Oct 24 22:53 ./
drwxr-xr-x+ 34 mike  staff   1.1K Oct 24 22:04 ../
drwxr-xr-x  13 mike  staff   416B Oct 24 23:14 .git/
-rw-r--r--   1 mike  staff    10B Oct 24 22:04 .gitignore
-rw-r--r--   1 mike  staff   282B Oct 24 22:23 CHANGELOG.md
-rw-r--r--   1 mike  staff   1.6K Oct 24 22:59 README.md
drwxr-xr-x  10 mike  staff   320B Oct 24 22:04 conf/
-rwxr-xr-x   1 mike  staff    29K Oct 24 23:06 deva*
-rw-r--r--   1 mike  staff     2B Oct 24 22:52 update.txt
drwxr-xr-x   3 mike  staff    96B Oct 24 22:54 updates/
```

<img width="832" alt="screen shot 2017-10-24 at 23 17 10" src="https://user-images.githubusercontent.com/358114/31972728-8a23c894-b911-11e7-9052-a0fd39959a49.png">

If it helps, here's my user settings file:

```
{
    "explorer.autoReveal": false,
    "editor.renderWhitespace": "all",
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.fontSize": 13,
    "editor.formatOnPaste": true,
    "editor.wordWrap": "on",
    "editor.rulers": [80],
    "editor.minimap.enabled": false,
    "editor.folding": false,
    "editor.occurrencesHighlight": false,
    "editor.trimAutoWhitespace": false,
    "editor.renderIndentGuides": false,
    "explorer.openEditors.visible": 0,
    "extensions.ignoreRecommendations": false,
    "files.insertFinalNewline": true,
    "phpcs.standard": "PSR2",
    "phpmd.rules": "cleancode,codesize,controversial,design,unusedcode",
    "phpmd.verbose": true,
    "projectManager.showProjectNameInStatusBar": false,
    "sync.anonymousGist": false,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.gist": "--hidden--",
    "sync.lastUpload": "2017-10-19T20:47:44.446Z",
    "sync.lastDownload": "2017-09-24T23:06:45.148Z",
    "sync.forceDownload": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "trailing-spaces.highlightCurrentLine": false,
    "trailing-spaces.includeEmptyLines": false,
    "vsicons.presets.foldersAllDefaultIcon": true,
    "window.openFoldersInNewWindow": "off",
    "window.restoreFullscreen": true,
    "workbench.colorCustomizations": {
        "editorWhitespace.foreground": "#282c34",
        "editor.selectionHighlightBackground": "#233e5a",
        "sideBar.foreground": "#9da5b4"
    },
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "vscode-icons",
    "workbench.startupEditor": "newUntitledFile",
    "vsicons.dontShowNewVersionMessage": true
}
```

**Comment by timonwong** [comment]
@Swift-R Thanks, I finally located where the document start with 'git://' from: Microsoft/vscode#21324

So, they are just virtual documents that I need to filter them out in my plugin.

**Comment by dsifford** [comment]
@timonwong Nice! Good find.

Sorry for not getting back with you Re: your inquiry. The notification got buried in my inbox 😖

**Comment by timonwong** [comment]
v0.2.1 should address this issue
