### ISSUE TITLE
Provide quick fixes (editor actions) for violations

### ISSUE THREAD

**Issue by Ash258** [timonwong/vscode-shellcheck#45]
Extensions could register code actions, which could be invoked by user to provide fast syntax fixes.

For some violations it could be just simple find and replace (for example S2006). When `SC2006` violation occurs you simply select quick fixes -> Convert backticks to subshell notation and vscode automatically change it for you.

Same for double quotes (SC2086), let (SC2219), ...

![image](https://user-images.githubusercontent.com/13260377/54202411-3e436000-44d0-11e9-9569-70f32078aa7b.png)

Typescript as example: <https://code.visualstudio.com/Docs/languages/typescript#_quick-fixes>

**Comment by timonwong** [comment]
It's definitely a great feature, but I'm sorry to tell you I may not implement that myself :(  (PRs are welcome though)
Just because ’quick fix‘ is not that easy to implement well, unless you roll your own language server, and I got little spare time...

**Comment by David-Else** [comment]
The latest shellcheck release notes say the next version has work on:

> Preliminary support for fix suggestions

https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md

:)

**Comment by timonwong** [comment]
#70 Provide basic support to "Auto Fix" feature, shellcheck v0.7.0 or better is required.

For early birds builds, please visit: https://timonwong.visualstudio.com/_apis/resources/Containers/4316436?itemPath=vsix%2Fshellcheck-1.0.0-alpha.vsix

**Comment by timonwong** [comment]
v0.9.0 released. In order to get this work,  shellcheck v0.7.0 or better is required, and, "shellcheck.enableQuickFix" should be "true" as well.
