### ISSUE TITLE
Disable for zsh files

### ISSUE THREAD

**Issue by robsonpeixoto** [timonwong/vscode-shellcheck#46]
When I open a ZSH file it show the message:
> ShellCheck only supports sh/bash/dash/ksh scripts. Sorry! [SC1071]shellcheck(1071)

And for file without the shebang, it show:
> Tips depend on target shell and yours is unknown. Add a shebang. [SC2148]shellcheck(2148)

IMHO, if the file has the extension `zsh` the plugin should be disabled.

**Comment by timonwong** [comment]
Thanks for your suggestion, I'll ignore `.zsh` files by default then.

For now, you can configure it through `"shellcheck.ignorePatterns"`:

```json
{
    "shellcheck.exclude": {
          "**/*.zsh": true
    }
}
```
