### ISSUE TITLE
Can't configure shellcheck located in workspace

### ISSUE THREAD

**Issue by bryceschober** [timonwong/vscode-shellcheck#48]
I've built a project that includes the shellcheck executable in a sub-directory, and have tried and failed to use a workspace setting to point your extension to it. I've tried both a relative path like `external/shellcheck` and `./external/shellcheck`, but both result in the "shellcheck program was not found" error message after saving the setting...

**Comment by bryceschober** [comment]
Is there some other method to find a workspace-installed shellcheck executable?

**Comment by biplobsd** [comment]
same problem

**Comment by timonwong** [comment]
In v0.7.0, you can use `${workspaceRoot}` in `executablePath` now.
