### ISSUE TITLE
(Request) Include dropdown links to 'For more information: ' WIKI articles on each problem in the problems panel

### ISSUE THREAD

**Issue by David-Else** [timonwong/vscode-shellcheck#51]
Hi, thanks for the awesome extension. It would be fantastic if it could provide a link to the WIKI for the problem just like https://github.com/Microsoft/vscode-eslint does. I think this functionality was added semi recently to vs code.

I note when shellcheck is used on the command line each problem has a link generated and clickable, for example:
```
For more information:
  https://www.shellcheck.net/wiki/SC1087 -- Use braces when expanding arrays,...
  https://www.shellcheck.net/wiki/SC2034 -- assoc appears unused. Verify use ...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```
Could this information not be passed to the extension and provided in a drop down menu in the VS Code problems panel? Like in eslint just click the problem and choose 'show documentation for SC1087 -- Use braces when expanding arrays,...'
![link-to-docs](https://user-images.githubusercontent.com/12832280/55868417-57e1d100-5b7c-11e9-9ac0-bff6d0b82300.png)

Shellcheck 0.6 added 

> Command line option --wiki-link-count/-W for showing wiki links

, maybe that helps?

Before you ask, sorry I am not able to do this myself, I don't have the required knowledge.

Cheers!

**Comment by timonwong** [comment]
eslint do implement language server, so it can provide more features than any other linters based on "diagnostics" API.

It's not an easy task, similar in #45.

In order to provide those features, LSP need to be implemented...

**Comment by timonwong** [comment]
v0.8.0 release provide such functionality :)

![image](https://user-images.githubusercontent.com/1398228/62270521-c1a62380-b468-11e9-902d-d3df9dd43496.png)

**Comment by David-Else** [comment]
AWESOME!!! :)
