### ISSUE TITLE
cat << heredoc fails in IDE, while shellcheck not complaining

### ISSUE THREAD

**Issue by jannick0** [timonwong/vscode-shellcheck#52]
The code snip (a simplified part of a `configure` script created by `autoconf`)
~~~sh
#! /usr/bin/sh
cat << _ACEOF
abc
_ACEOF
~~~
passes the smell test when `shellcheck` (0.6.0) is **directly** invoked. However, in the IDE `cat <<` is underlined in red with the tooltip saying `Failed to parse expression`.

I am wondering if this is a bug?

Many thanks.

**Comment by timonwong** [comment]
I suppose it's caused by other extension, you can verify your installed extensions that provide additional features to bash/shellscripts.

**Comment by jannick0** [comment]
Spot on: After switching off another culprit extension for shell scripts, shellcheck does not complain about anything in most lengthy configure scripts any more.

Many thanks!
