### ISSUE TITLE
Do not treat SC2145 as a error

### ISSUE THREAD

**Issue by sr229** [timonwong/vscode-shellcheck#74]
If we read [SC2145](https://github.com/koalaman/shellcheck/wiki/SC2145) the wiki implies that this is basically to warn about the implications of using `$@` over `$*`.

**Comment by timonwong** [comment]
In shellcheck itself, the severity level for SC2145 is actually "error". If you insist it's a warning, please fire an issue to shellcheck instead.

**Comment by timonwong** [comment]
```json
{
  "comments": [
    {
      "file": "x.sh",
      "line": 3,
      "endLine": 3,
      "column": 39,
      "endColumn": 41,
      "level": "error",
      "code": 2145,
      "message": "Argument mixes string and array. Use * or separate argument.",
      "fix": null
    }
  ]
}
```
