### ISSUE TITLE
Do not works for untitled documents (not saved)

### ISSUE THREAD

**Issue by ColCh** [timonwong/vscode-shellcheck#75]
Debug line for that

`[DEBUG] Spawn: /usr/bin/env shellcheck -f json -`

so there is no file and shellcheck fails. and, it seems that `shellcheck` not supports passing file content either

but that's okay

what if this extension would create temp file and use it for untitled document?

I may try to help with PR [because I heavily need this feature] but this feature needs to be discussed a bit

**Comment by ColCh** [comment]
Oopsie it's working

sorry! My fault

**Comment by sylveon** [comment]
The little - after JSON means the extension passes the content to check via standard input to shellcheck
