### ISSUE TITLE
Reporting errors on .git files (returns)

### ISSUE THREAD

**Issue by loudsquelch** [timonwong/vscode-shellcheck#78]
Hi,

My vscode just self-updated to 1.41.0 and I am now seeing behaviour similar to that reported in issue #4 and resolved in v0.2.1.  Here is a screenshot of what I am seeing:

![issue](https://user-images.githubusercontent.com/35978618/70937161-bfb9b700-203b-11ea-9c51-13a4dcec1be2.png)

![issue2](https://user-images.githubusercontent.com/35978618/70938193-9f8af780-203d-11ea-8636-ad48933eb319.png)

I only have the one shellcheck option set in vscode:
`"shellcheck.executablePath": "C:\\Apps\\shellcheck\\shellcheck-stable.exe"`

**Comment by Stanzilla** [comment]
Same here, have you tried the extension version from before the fix from #4?

**Comment by timonwong** [comment]
Thanks for reporting, needs time investigating what happened in vscode (again) 😂

**Comment by timonwong** [comment]
It seems that a new scheme "gitfs" is introduced, I'll fix it later
