### ISSUE TITLE
How to ignore DevOps tokens #{*}#

### ISSUE THREAD

**Issue by spitfire184** [timonwong/vscode-shellcheck#84]
Hi,

I'm trying to get shellcheck to ignore tokens in a file. They take the format #{variableName}#

This is what I have tried in my VS Code workspace settings:

```
	"settings": {
		"shellcheck.ignorePatterns": {
			"#\\{*\\}#": true
		}
	}
```
However, this doesn't work. Could anyone offer guidance?

**Comment by gromgit** [comment]
I don't use this extension, but a quick search for `ignorePatterns` in this repo dug up the following in `package.json`:
```
				"shellcheck.ignorePatterns": {
					"description": "Matching files and directories are being ignored by shellcheck. Glob patterns are interpreted relative to the workspace's root folder.",
					"type": "object",
					"scope": "resource",
					"additionalProperties": {
						"anyOf": [
							{
								"type": "boolean",
								"description": "The glob pattern to match file paths against. Set to true or false to enable or disable the pattern."
							}
						]
					},
					"default": {
						"**/*.zsh": true
					}
				},
```
Note that it matches against _pathnames_, not file content. What you're asking for doesn't seem to be doable in either shellcheck itself or this VSCode extension.

**Comment by spitfire184** [comment]
Thanks for clearing that up. I don't know whether it's your profile picture but I hang my head in shame.
