### ISSUE TITLE
Make snap vscode and snap shellcheck work together

### ISSUE THREAD

**Issue by dominiksalvet** [timonwong/vscode-shellcheck#85]
Hello vscode-shellcheck developers! :wave: 

First I want to **thank you** @timonwong for developing this extension. :heart:  It is just awesome! :+1: :smile: 

One thing I am still missing, though. As you may know, snap (or flatpak) has the most recent version of available software most of the time. And hence, in my case, I can install **shellcheck 0.4.6** from apt repositories (Ubuntu 18.04) or **shellcheck 0.7.0** from snap. So I am using the snap version, which is also incorporated in *PATH*, so I can invoke it simply by `shellcheck` command.

However, this extension **does not detect my shellcheck snap installation** and prints `[INFO] shellcheck version: null`.
* Even using full path */snap/bin/shellcheck* didn't help.
* I have also tried to create a script wrapper in my home binary directory *~/.local/bin* (which is also in *PATH*) but that didn't work as well.
* Installing shellcheck without "sandboxing" (unconfined) `sudo snap install --classic shellcheck` also didn't help.

These symptoms are quite strange since **vscode itself is also installed without sandbox** and it should be able to access it. It would be great to see a snap vscode and a snap shellcheck work together as I want  to have the most recent version of both with the comfort of snap. :smile: What do you think? :thinking: 

Thank you for your time. :purple_heart: 

---

Once shellcheck is installed from apt, it works (with a snap vscode). Once vscode is installed using the official deb file, it works (with a snap shellcheck). Once both are installed from snap, it does not work.

> If it is not possible to resolve this issue, it looks like the best approach is to have a snap shellcheck and a deb vscode as it seems that it also sets up a vscode ppa for apt updates.

**Comment by dominiksalvet** [comment]
It seems that as described in a [post](https://github.com/timonwong/vscode-shellcheck/issues/50#issuecomment-511171979) of #50, @saxonww also experienced the same issue.

**Comment by timonwong** [comment]
Sounds like a apparmor issue, sadly I'm not familiar with...

Since v0.10.0, precompiled binaries are bundled in the extension now, can you verify that?  (`shellcheck.executablePath` should be unset)

**Comment by saxonww** [comment]
I was able to install the `code` snap on Ubuntu 20.04, then install this extension and use it.

I suspect that it still wouldn't work with the separate `shellcheck` snap, but since you're bundling the executable now it doesn't matter.

**Comment by dominiksalvet** [comment]
Good work @timonwong! Although it does not use the snap shellcheck (0.7.0 on my system), it works with its bundled one (0.7.1 version). Unfortunately, I cannot confirm this behavior on a snap version of VSCode as I am currently using a DEB version... But together with the @saxonww's post, I think that this issue has been resolved and may be closed.
