### ISSUE TITLE
request: Option to do `shellcheck -x`

### ISSUE THREAD

**Issue by sparr** [timonwong/vscode-shellcheck#86]
I want shellcheck to follow `source` lines into other scripts, which requires the command `shellcheck -x`.

**Comment by dampcake** [comment]
You should be able to add a custom args via:
`"shellcheck.customArgs": ["-x"]`
in settings.json.

**Comment by felipecassiors** [comment]
This is already covered as @dampcake said. Are you talking about making it default?

**Comment by felipecrs** [comment]
This is already supported, as @dampcake stated.
