### ISSUE TITLE
Extension not working with WSL enabled

### ISSUE THREAD

**Issue by theAkito** [timonwong/vscode-shellcheck#87]
Error:
```
Got told to use WSL, but cannot find installation. Bailing out.
```

Looking at this:
https://github.com/timonwong/vscode-shellcheck/blob/77b03afd1d8007b48eaa6351e3f9cc3b0c2be544/src/utils/wslSupport.ts#L23-L24

Because of this:
https://github.com/timonwong/vscode-shellcheck/blob/77b03afd1d8007b48eaa6351e3f9cc3b0c2be544/src/linter.ts#L247-L249

I checked if there is a `bash.exe` in `C:\Windows\System32`. It is there and works, as it should.

The difference is, that the actual directory where the actual WSL is installed, is in a custom place, not in the default directory within `AppData\xxx\`. However, since it is asking for `bash.exe` which is at the right place and confirmed to work, I don't understand why the extension cannot find the WSL installation, which is, again, working perfectly fine with all other extensions for VS Code, installed in WSL.

**Comment by GregorySWI** [comment]
I am getting the same error after installing the April VSCode update. WSL is installed in the default location.

**Comment by theAkito** [comment]
This bug is fucking annoying. Tested on another installation with WSL 2. When I installed `shellcheck` from official repositories, it detected my `shellcheck` and told me to update. Once I updated manually, the extension does not find the binary anymore! Brains over 9000!

**Comment by wscherphof** [comment]
I wonder if this is correct (not WSL if not Windows?):

https://github.com/timonwong/vscode-shellcheck/blob/77b03afd1d8007b48eaa6351e3f9cc3b0c2be544/src/utils/wslSupport.ts#L18-L21

Also, maybe the `wslSupport` code might be WSL1-specific, and problematic in WSL2?

**Comment by vbrozik** [comment]
I was using the plugin for few months without problems. Unfortunately I started to get the error message probably after changing my default WSL distribution to a WSL2 one.

Changing the default WSL distribution to the original WSL1 one (I did not delete it yet) did not remove the problem so its start could be related to these or other changes:
- upgrading Windows 10 from 1904 to 2004
- upgrading VS Code
- upgrading vscode-shellcheck plugin
- updating Ubuntu distro in WSL
...

**Comment by felipecrs** [comment]
@vbrozik It might not fix your exact problem, but did you notice that now the extension has the `shellcheck` binaries bundled in it? For both Windows and Linux. To use it, unset the  _Shellcheck: Executable Path_.

**Comment by felipecrs** [comment]
@timonwong perhaps we should deprecate the WSL feature of the extension since the Windows binaries are included in it.

**Comment by gostega** [comment]
I am developing in WSL (i.e. using the VSCode remote WSL server option). Trying to use this extension but getting that error.
I've tried with all combinations of "Use WSL" in the User, Workspace and WSL tabs of the extension settings checked and unchecked. If I have them all unchecked, I get no error but nothing happens at all either.

**Comment by felipecrs** [comment]
The "Use WSL" option should be unticked. Don't use that option.

Also, make sure the extension is installed in your WSL side, and not in the Windows side. 

Then, if that still doesn't work, can you record a GIF and post here? I use Sharex to do that.

**Comment by gostega** [comment]
I ended up getting a new computer, and it just worked first time when I installed shellcheck extension in VSCode (in a project I was working on in WSL). I don't have access to the old computer anymore unfortunately so cannot reproduce the error anymore.
