### ISSUE TITLE
Can't follow files even using -x

### ISSUE THREAD

**Issue by brianjmurrell** [timonwong/vscode-shellcheck#91]
Issue Type: <b>Bug</b>

I have:

```
    "shellcheck.customArgs": [
        "-x"
    ],
```
in my `settings.json`, however shellcheck still cannot follow sourced files.

I get an error message:

```
Not following: ci/parse_ci_envs.sh: openBinaryFile: does not exist (No such file or directory)shellcheck(SC1091)
```

The file most certainly exists and `shellcheck -x` from the command line in the same directory as the project follows it just fine.

Extension version: 0.9.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.6.8-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2182)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.28GB (4.38GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by felipecassiors** [comment]
Mine is working fine:

![image](https://user-images.githubusercontent.com/29582865/90057113-50719100-dcb6-11ea-8771-8bcb9af8fa5d.png)

**Comment by timonwong** [comment]
@brianjmurrell By default, the cwd of shellcheck is set to the file being linted, can you have a try enabling `useWorkspaceRootAsCwd`?  More info #25

**Comment by brianjmurrell** [comment]
Just knowing that the path is relative to the file being linted, and not the root of the workspace is enough.  I can just fix my relative paths.
