### ISSUE TITLE
Is this repository going to be maintained?

### ISSUE THREAD

**Issue by felipecassiors** [timonwong/vscode-shellcheck#92]
Hi @timonwong, sorry for the question, but do you still plan to keep this repository/project active?

I'm questioning because I'm considering forking it and implement some features in case you say no.

**Comment by beltaurus** [comment]
Isn't the point of Open Source that it stays alive through participation of all?
I find that forking software tends to introduce more confusion than required. Why not implement those features and submit here?
And if @timonwong is ready to share or transfer his repository administration privileges, the repository goes on...
Unless the features to be implemented are rejected, but I don't see any history of that?

Just trying to avoid unnecessary choices...

**Comment by felipecassiors** [comment]
I totally agree. 

I questioning because I have one PR open and there's also another which didn't receive any interaction so far from the maintainers (if there is more than one).

As you said, the path is to try to avoid forking as much as possible. Would be good to see if @timonwong considers alternatives such as adding maintainers or moving this repository to an organization.

**Comment by timonwong** [comment]
Hi @felipecassiors, sorry for my late response. You're right due to my procrastination currently this repo seems inactive, and indeed new maintainers are welcome, I'll open a new thread for that.

**Comment by timonwong** [comment]
#93 
@felipecassiors Are you interested to be a maintainer of this project :)  ?

**Comment by felipecassiors** [comment]
> @felipecassiors Are you interested to be a maintainer of this project :) ?

For sure! I use this extension my entire day, it would be a pleasure to help it to keep going on. :)

**Comment by timonwong** [comment]
> For sure! I use this extension my entire day, it would be a pleasure to help it to keep going on. :)

Invitation sent, please have a look at your email, thanks and welcome :) 🎉

**Comment by felipecassiors** [comment]
> @felipecassiors Invitation sent, please have a look at your email, thanks and welcome :) 🎉

Awesome! 

I'm going to close this issue, it's already answered.
